/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "E:\\vuepress\\docs\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-71c293f3",
    path: "/ui/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-71c293f3").then(next)
    },
  },
  {
    path: "/ui/index.html",
    redirect: "/ui/"
  },
  {
    path: "/00.目录页/02.页面.html",
    redirect: "/ui/"
  },
  {
    name: "v-c25d0578",
    path: "/web/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c25d0578").then(next)
    },
  },
  {
    path: "/web/index.html",
    redirect: "/web/"
  },
  {
    path: "/00.目录页/01.前端.html",
    redirect: "/web/"
  },
  {
    name: "v-3878b114",
    path: "/more/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3878b114").then(next)
    },
  },
  {
    path: "/more/index.html",
    redirect: "/more/"
  },
  {
    path: "/00.目录页/04.更多.html",
    redirect: "/more/"
  },
  {
    name: "v-e02d5534",
    path: "/pages/b5e9e9/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e02d5534").then(next)
    },
  },
  {
    path: "/pages/b5e9e9/index.html",
    redirect: "/pages/b5e9e9/"
  },
  {
    path: "/01.前端/25.JavaScript文章/02.new命令的原理.html",
    redirect: "/pages/b5e9e9/"
  },
  {
    name: "v-7100b3bc",
    path: "/archives/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7100b3bc").then(next)
    },
  },
  {
    path: "/archives/index.html",
    redirect: "/archives/"
  },
  {
    path: "/@pages/archivesPage.html",
    redirect: "/archives/"
  },
  {
    name: "v-05bae60a",
    path: "/technology/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-05bae60a").then(next)
    },
  },
  {
    path: "/technology/index.html",
    redirect: "/technology/"
  },
  {
    path: "/00.目录页/03.技术.html",
    redirect: "/technology/"
  },
  {
    name: "v-fcc9e9fc",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fcc9e9fc").then(next)
    },
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    path: "/@pages/categoriesPage.html",
    redirect: "/categories/"
  },
  {
    name: "v-d7b53bb0",
    path: "/pages/0500c5/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-d7b53bb0").then(next)
    },
  },
  {
    path: "/pages/0500c5/index.html",
    redirect: "/pages/0500c5/"
  },
  {
    path: "/01.前端/30.Vue文章/02.vue项目开发的一些准备工作.html",
    redirect: "/pages/0500c5/"
  },
  {
    name: "v-8e380ebc",
    path: "/tags/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8e380ebc").then(next)
    },
  },
  {
    path: "/tags/index.html",
    redirect: "/tags/"
  },
  {
    path: "/@pages/tagsPage.html",
    redirect: "/tags/"
  },
  {
    name: "v-43e3ee74",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-43e3ee74").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]