/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "路远行至",
  "description": "web前端技术博客,简洁至上,专注web前端学习与总结。JavaScript,js,ES6,TypeScript,vue,python,css3,html5,Node,git,github等技术文章。",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/img/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "前端博客,个人技术博客,前端,前端开发,前端框架,web前端,前端面试题,技术文档,学习,面试,JavaScript,js,ES6,TypeScript,vue,python,css3,html5,Node,git,github,markdown"
      }
    ],
    [
      "meta",
      {
        "name": "baidu-site-verification",
        "content": "7F55weZDDc"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#11a8cd"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "title": "页面",
      "frontmatter": {
        "pageComponent": {
          "name": "Catalogue",
          "data": {
            "key": "02.页面",
            "imgUrl": "/img/ui.png",
            "description": "html(5)/css(3),前端页面相关技术"
          }
        },
        "title": "页面",
        "date": "2020-11-18T22:11:40.000Z",
        "permalink": "/ui/",
        "sidebar": false,
        "article": false,
        "comment": false,
        "editLink": false
      },
      "regularPath": "/00.%E7%9B%AE%E5%BD%95%E9%A1%B5/02.%E9%A1%B5%E9%9D%A2.html",
      "relativePath": "00.目录页/02.页面.md",
      "key": "v-71c293f3",
      "path": "/ui/"
    },
    {
      "title": "前端",
      "frontmatter": {
        "pageComponent": {
          "name": "Catalogue",
          "data": {
            "key": "01.前端",
            "imgUrl": "/img/web.png",
            "description": "JavaScript、ES6、Vue框架等前端技术"
          }
        },
        "title": "前端",
        "date": "2020-11-118 21:50:53",
        "permalink": "/web",
        "sidebar": false,
        "article": false,
        "comment": false,
        "editLink": false
      },
      "regularPath": "/00.%E7%9B%AE%E5%BD%95%E9%A1%B5/01.%E5%89%8D%E7%AB%AF.html",
      "relativePath": "00.目录页/01.前端.md",
      "key": "v-c25d0578",
      "path": "/web/"
    },
    {
      "title": "更多",
      "frontmatter": {
        "pageComponent": {
          "name": "Catalogue",
          "data": {
            "key": "04.更多",
            "imgUrl": "/img/more.png",
            "description": "学习、面试、在线工具等更多文章和页面"
          }
        },
        "title": "更多",
        "date": "2020-11-18T22:12:09.000Z",
        "permalink": "/more",
        "sidebar": false,
        "article": false,
        "comment": false,
        "editLink": false
      },
      "regularPath": "/00.%E7%9B%AE%E5%BD%95%E9%A1%B5/04.%E6%9B%B4%E5%A4%9A.html",
      "relativePath": "00.目录页/04.更多.md",
      "key": "v-3878b114",
      "path": "/more/"
    },
    {
      "title": "new命令的原理",
      "frontmatter": {
        "title": "new命令的原理",
        "date": "2020-11-18T22:15:46.000Z",
        "permalink": "/pages/b5e9e9/",
        "categories": [
          "前端",
          "JavaScript文章"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/01.%E5%89%8D%E7%AB%AF/25.JavaScript%E6%96%87%E7%AB%A0/02.new%E5%91%BD%E4%BB%A4%E7%9A%84%E5%8E%9F%E7%90%86.html",
      "relativePath": "01.前端/25.JavaScript文章/02.new命令的原理.md",
      "key": "v-e02d5534",
      "path": "/pages/b5e9e9/"
    },
    {
      "title": "归档",
      "frontmatter": {
        "archivesPage": true,
        "title": "归档",
        "permalink": "/archives/",
        "article": false
      },
      "regularPath": "/@pages/archivesPage.html",
      "relativePath": "@pages/archivesPage.md",
      "key": "v-7100b3bc",
      "path": "/archives/"
    },
    {
      "title": "技术",
      "frontmatter": {
        "pageComponent": {
          "name": "Catalogue",
          "data": {
            "key": "03.技术",
            "imgUrl": "/img/other.png",
            "description": "技术文档、教程、技巧、总结等文章"
          }
        },
        "title": "技术",
        "date": "2020-11-18T22:11:53.000Z",
        "permalink": "/technology",
        "sidebar": false,
        "article": false,
        "comment": false,
        "editLink": false
      },
      "regularPath": "/00.%E7%9B%AE%E5%BD%95%E9%A1%B5/03.%E6%8A%80%E6%9C%AF.html",
      "relativePath": "00.目录页/03.技术.md",
      "key": "v-05bae60a",
      "path": "/technology/"
    },
    {
      "title": "分类",
      "frontmatter": {
        "categoriesPage": true,
        "title": "分类",
        "permalink": "/categories/",
        "article": false
      },
      "regularPath": "/@pages/categoriesPage.html",
      "relativePath": "@pages/categoriesPage.md",
      "key": "v-fcc9e9fc",
      "path": "/categories/"
    },
    {
      "title": "vue项目开发的一些准备工作",
      "frontmatter": {
        "title": "vue项目开发的一些准备工作",
        "date": "2020-11-18T22:29:40.000Z",
        "permalink": "/pages/0500c5/",
        "categories": [
          "前端",
          "Vue文章"
        ],
        "tags": [
          null
        ]
      },
      "regularPath": "/01.%E5%89%8D%E7%AB%AF/30.Vue%E6%96%87%E7%AB%A0/02.vue%E9%A1%B9%E7%9B%AE%E5%BC%80%E5%8F%91%E7%9A%84%E4%B8%80%E4%BA%9B%E5%87%86%E5%A4%87%E5%B7%A5%E4%BD%9C.html",
      "relativePath": "01.前端/30.Vue文章/02.vue项目开发的一些准备工作.md",
      "key": "v-d7b53bb0",
      "path": "/pages/0500c5/"
    },
    {
      "title": "标签",
      "frontmatter": {
        "tagsPage": true,
        "title": "标签",
        "permalink": "/tags/",
        "article": false
      },
      "regularPath": "/@pages/tagsPage.html",
      "relativePath": "@pages/tagsPage.md",
      "key": "v-8e380ebc",
      "path": "/tags/"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Hammer's blog",
        "tagline": "栽培剪伐须勤力，花易凋零草易生。",
        "features": [
          {
            "title": "前端",
            "details": "JavaScript、ES6、Vue框架等前端技术",
            "link": "/web/",
            "imgUrl": "/img/web.png"
          },
          {
            "title": "页面",
            "details": "html(5)/css(3)，前端页面相关技术",
            "link": "/ui/",
            "imgUrl": "/img/ui.png"
          },
          {
            "title": "技术",
            "details": "技术文档、教程、技巧、总结等文章",
            "link": "/technology/",
            "imgUrl": "/img/other.png"
          }
        ]
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-43e3ee74",
      "path": "/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "首页",
        "link": "/"
      },
      {
        "text": "前端",
        "link": "/web/",
        "items": [
          {
            "text": "学习笔记",
            "items": [
              {
                "text": "JavaScript",
                "link": "/pages/b5e9e9/"
              },
              {
                "text": "Vue",
                "link": "/pages/0500c5/"
              }
            ],
            "item": [
              {
                "text": "《JavaScript教程》笔记",
                "link": ""
              },
              {
                "text": "《JavaScript高级程序设计》笔记",
                "link": ""
              },
              {
                "text": "《Es6教程》笔记",
                "link": ""
              },
              {
                "text": "《Vue》笔记",
                "link": ""
              },
              {
                "text": "《TypeScript教程》笔记",
                "link": ""
              },
              {
                "text": "《Git》笔记",
                "link": ""
              }
            ]
          }
        ]
      },
      {
        "text": "页面",
        "link": "/ui/",
        "items": [
          {
            "text": "HTML",
            "link": "/pages/8309a5b876fc95e3/"
          },
          {
            "text": "CSS",
            "link": "/pages/0a83b083bdf257cb/"
          }
        ]
      },
      {
        "text": "技术",
        "link": "/technology/",
        "items": [
          {
            "text": "技术文档",
            "link": "/pages/9a7ee40fc232253e/"
          },
          {
            "text": "GitHub技巧",
            "link": "/pages/4c778760be26d8b3/"
          },
          {
            "text": "Nodejs",
            "link": "/pages/117708e0af7f0bd9/"
          },
          {
            "text": "博客搭建",
            "link": "/pages/41f87d890d0a02af/"
          }
        ]
      },
      {
        "text": "更多",
        "link": "/more/",
        "items": [
          {
            "text": "学习",
            "link": "/pages/f2a556/"
          },
          {
            "text": "面试",
            "link": "/pages/aea6571b7a8bae86/"
          },
          {
            "text": "心情杂货",
            "link": "/pages/2d615df9a36a98ed/"
          },
          {
            "text": "实用技巧",
            "link": "/pages/baaa02/"
          },
          {
            "text": "友情链接",
            "link": "/friends/"
          }
        ]
      },
      {
        "text": "关于",
        "link": "/about/"
      },
      {
        "text": "收藏",
        "link": "/pages/beb6c0bd8a66cea6/",
        "items": [
          {
            "text": "网站",
            "link": "/pages/beb6c0bd8a66cea6/"
          },
          {
            "text": "资源",
            "link": "/pages/eee83a9211a70f9d/"
          },
          {
            "text": "Vue资源",
            "link": "/pages/12df8ace52d493f6/"
          }
        ]
      },
      {
        "text": "索引",
        "link": "/archives/",
        "items": [
          {
            "text": "分类",
            "link": "/categories/"
          },
          {
            "text": "标签",
            "link": "/tags/"
          },
          {
            "text": "归档",
            "link": "/archives/"
          }
        ]
      }
    ],
    "logo": "/img/logo.jpeg",
    "sidebar": {
      "/00.目录页/": [
        [
          "01.前端.md",
          "前端",
          "/web"
        ],
        [
          "02.页面.md",
          "页面",
          "/ui/"
        ],
        [
          "03.技术.md",
          "技术",
          "/technology"
        ],
        [
          "04.更多.md",
          "更多",
          "/more"
        ]
      ],
      "catalogue": {
        "前端": "/web",
        "页面": "/ui/",
        "技术": "/technology",
        "更多": "/more"
      },
      "/01.前端/": [
        {
          "title": "JavaScript文章",
          "collapsable": true,
          "children": [
            [
              "25.JavaScript文章/02.new命令的原理.md",
              "new命令的原理",
              "/pages/b5e9e9/"
            ]
          ]
        },
        {
          "title": "Vue文章",
          "collapsable": true,
          "children": [
            [
              "30.Vue文章/02.vue项目开发的一些准备工作.md",
              "vue项目开发的一些准备工作",
              "/pages/0500c5/"
            ]
          ]
        }
      ]
    },
    "author": {
      "name": "Hammer King",
      "link": "https://github.com/xugaoyi"
    },
    "blogger": {
      "avatar": "/img/avatar.jpg",
      "name": "Hammer King",
      "slogan": "真的有这么丝滑吗"
    },
    "social": {
      "icons": [
        {
          "iconClass": "icon-youjian",
          "title": "发邮件",
          "link": "mailto:906659553@qq.com"
        },
        {
          "iconClass": "icon-github",
          "title": "GitHub",
          "link": "https://github.com/xugaoyi"
        }
      ]
    },
    "footer": {
      "createYear": 2019,
      "copyrightInfo": "Hammer King | MIT License"
    }
  }
}